RGBLIGHT_ENABLE = yes

OLED_ENABLE = yes

#以下独自設定
EXTRAKEY_ENABLE = yes
MACRO_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no

# 容量削減
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENEBLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_MODE = no
